### ISSUE TITLE
Bringing your attention to another solution for the underlying library

### ISSUE THREAD

**Issue by costastf** [boltgolt/ovchipHA#1]
Not an issue, just wanted to let you know of this http://ovchipcardlib.readthedocs.io/en/latest/ that is a much better implementation (by me) of the ovchip than the one you are using for this project, if you care about it of course :)

**Comment by boltgolt** [comment]
I found that the official OVchip API has a +/- 7 minute delay in it, which was unacceptable for my use case. The NS app also has a page with card events on it and they update in about 5 seconds, so i [reverse engineered](https://github.com/Boltgolt/nslib) that. Thanks a lot for the tip and taking the time to check this repo out though! 😊
